tests:
	../vendor/bin/phpunit --bootstrap ../vendor/autoload.php --testdox optionsTest.php
	../vendor/bin/phpunit --bootstrap ../vendor/autoload.php --testdox fileExistsTest.php
	../vendor/bin/phpunit --bootstrap ../vendor/autoload.php --testdox fileEncodingTest.php
	../vendor/bin/phpunit --bootstrap ../vendor/autoload.php --testdox fileEolTest.php